apiVersion: v1
kind: Service
metadata:
  name: server-svc2
  namespace: app-stage2
  annotations:
    metallb.universe.tf/loadbalancerIPs: 192.168.10.15
spec:
  type: LoadBalancer
  selector: 
    app: go-http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080